CREATE TABLE user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    role VARCHAR(20) NOT NULL,
    knowledge_bases VARCHAR(500),
    CONSTRAINT uk_user_accounts_username UNIQUE (username)
);

CREATE TABLE document_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base VARCHAR(60) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    size_bytes BIGINT NOT NULL,
    content_type VARCHAR(255),
    owner VARCHAR(80),
    uploaded_by VARCHAR(100),
    uploaded_at VARCHAR(255),
    last_indexed_at VARCHAR(255),
    index_status VARCHAR(16),
    chunk_count INTEGER NOT NULL,
    error VARCHAR(500),
    file_hash VARCHAR(64),
    CONSTRAINT uk_document_files_kb_file UNIQUE (knowledge_base, file_name)
);

CREATE TABLE knowledge_gaps (
    id VARCHAR(255) PRIMARY KEY,
    knowledge_base VARCHAR(255) NOT NULL,
    question VARCHAR(2000) NOT NULL,
    session_id VARCHAR(255),
    created_at VARCHAR(255),
    occurrences INTEGER NOT NULL,
    last_asked_at VARCHAR(255)
);

CREATE TABLE audit_events (
    id VARCHAR(255) PRIMARY KEY,
    timestamp VARCHAR(255) NOT NULL,
    actor VARCHAR(255),
    action VARCHAR(60) NOT NULL,
    knowledge_base VARCHAR(255),
    file_name VARCHAR(255),
    details TEXT
);

CREATE TABLE knowledge_bases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at VARCHAR(40) NOT NULL,
    updated_at VARCHAR(40) NOT NULL,
    CONSTRAINT uk_knowledge_base_name UNIQUE (name)
);

CREATE TABLE knowledge_base_owners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base VARCHAR(60) NOT NULL,
    username VARCHAR(100) NOT NULL,
    created_at VARCHAR(40) NOT NULL,
    CONSTRAINT uk_knowledge_base_owner UNIQUE (knowledge_base, username)
);

CREATE INDEX idx_document_files_knowledge_base ON document_files (knowledge_base);
CREATE INDEX idx_knowledge_gaps_kb_last_asked ON knowledge_gaps (knowledge_base, last_asked_at);
CREATE INDEX idx_audit_events_timestamp ON audit_events (timestamp);
CREATE INDEX idx_kb_owners_username ON knowledge_base_owners (username);
